const $=(q,el=document)=>el.querySelector(q);const $$=(q,el=document)=>Array.from(el.querySelectorAll(q));document.getElementById('year').textContent=new Date().getFullYear();
const state={kits:[],reviews:[],filters:{q:'',cat:'all',scale:'all',sort:'rating-desc'}};const els={cards:document.getElementById('cards'),q:document.getElementById('searchInput'),cat:document.getElementById('categorySelect'),scale:document.getElementById('scaleSelect'),sort:document.getElementById('sortSelect'),addKitModal:document.getElementById('addKitModal'),addKitForm:document.getElementById('addKitForm'),reviewModal:document.getElementById('reviewModal'),reviewForm:document.getElementById('reviewForm'),reviewTitle:document.getElementById('reviewTitle')};
async function loadData(){const res=await fetch('data.json');const base=await res.json();const saved=JSON.parse(localStorage.getItem('makett-data')||'{}');state.kits=(saved.kits||base.kits);state.reviews=(saved.reviews||base.reviews);document.getElementById('kpiKits').textContent=String(state.kits.length);document.getElementById('kpiReviews').textContent=String(state.reviews.length);window.dispatchEvent(new CustomEvent('makett:data',{detail:{kits:state.kits,reviews:state.reviews}}));render()}
function saveData(){localStorage.setItem('makett-data',JSON.stringify({kits:state.kits,reviews:state.reviews}))}
function computeAvgRating(id){const list=state.reviews.filter(r=>r.kitId===id);if(!list.length)return 0;return list.reduce((s,r)=>s+r.rating,0)/list.length}
function renderStars(v){const r=Math.round(v);let h='<div class=\"stars\">';for(let i=1;i<=5;i++){h+=`<span class=\"star ${i<=r?'filled':''}\"></span>`}h+=`<span class=\"rating-text\">${v.toFixed(1)}</span></div>`;return h}
function applyFilters(list){let out=[...list];const {q,cat,scale,sort}=state.filters;if(q.trim()){const t=q.toLowerCase();out=out.filter(k=>k.name.toLowerCase().includes(t)||k.manufacturer.toLowerCase().includes(t))}if(cat!='all')out=out.filter(k=>k.category===cat);if(scale!='all')out=out.filter(k=>k.scale===scale);out=out.map(k=>({...k,avgRating:computeAvgRating(k.id)}));switch(sort){case 'rating-desc':out.sort((a,b)=>(b.avgRating||0)-(a.avgRating||0));break;case 'newest':out.sort((a,b)=>(b.releaseYear||0)-(a.releaseYear||0));break;case 'difficulty-asc':out.sort((a,b)=>(a.difficulty||0)-(b.difficulty||0));break;}return out}
function cardTemplate(k){return `<article class=\"card\">${k.coverUrl?`<img src=\"${k.coverUrl}\" alt=\"${k.name}\"/>`:`<img alt=\"placeholder\" src=\"https://picsum.photos/seed/${encodeURIComponent(k.name)}/640/360\">`}<div class=\"card-body\"><div class=\"card-title\"><div><h3>${k.name}</h3><div class=\"card-meta\">${k.manufacturer} • ${k.scale} • ${k.category}</div></div>${renderStars(k.avgRating||0)}</div><div class=\"card-meta\">Nehézség: ${'⭐'.repeat(k.difficulty||1)}</div><div class=\"card-actions\"><button class=\"btn\" data-action=\"review\" data-id=\"${k.id}\">Értékelés</button><span class=\"badge year\">${k.releaseYear||'—'}</span></div></div></article>`}
function render(){const list=applyFilters(state.kits);els.cards.innerHTML=list.map(cardTemplate).join('')||`<p>Nincs találat.</p>`}
els.q.addEventListener('input',e=>{state.filters.q=e.target.value;render()});els.cat.addEventListener('change',e=>{state.filters.cat=e.target.value;render()});els.scale.addEventListener('change',e=>{state.filters.scale=e.target.value;render()});els.sort.addEventListener('change',e=>{state.filters.sort=e.target.value;render()});
els.cards.addEventListener('click',e=>{const b=e.target.closest('button[data-action=\'review\']');if(!b)return;const id=b.dataset.id;const kit=state.kits.find(k=>k.id===id);if(!kit)return;els.reviewTitle.textContent=`Értékelés: ${kit.name}`;els.reviewForm.dataset.kitId=id;els.reviewForm.reset();els.reviewModal.showModal()});
els.reviewForm.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(els.reviewForm);const rating=Number(fd.get('rating'));const body=String(fd.get('body')||'').trim();if(!body||body.length<10){alert('A vélemény min. 10 karakter legyen.');return}const r={id:crypto.randomUUID(),kitId:els.reviewForm.dataset.kitId,user:'Vendég',rating,pros:String(fd.get('pros')||'')||undefined,cons:String(fd.get('cons')||'')||undefined,body,createdAt:new Date().toISOString()};state.reviews.unshift(r);saveData();els.reviewModal.close();render()});
document.addEventListener('click',(e)=>{if(e.target && e.target.id==='btnAddKit'){els.addKitForm.reset();els.addKitModal.showModal();}});
els.addKitForm?.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(els.addKitForm);const kit={id:crypto.randomUUID(),name:String(fd.get('name')),manufacturer:String(fd.get('manufacturer')),category:String(fd.get('category')),scale:String(fd.get('scale')),difficulty:Number(fd.get('difficulty')||3),releaseYear:fd.get('releaseYear')?Number(fd.get('releaseYear')):undefined,coverUrl:String(fd.get('coverUrl')||'')||undefined};state.kits.unshift(kit);saveData();els.addKitModal.close();render()});
loadData();